In [1]:
from os import listdir
from PIL import Image
import os.path
import numpy as np

path_new = 'C:/Users/Admin/Downloads/HMM/Proper/Exe/Experiment 1/Train 2'
h = 32 #height of image
w = 32 #width of image

#be careful with using this function, it will consume memory, access to disk and time
timid = []
for f in listdir(path_new):
    with open(os.path.join(path_new, f), 'rb') as img_set:
        img_arr = img_set.read(h*w)
        while img_arr:
            if len(img_arr) == h*w and img_arr not in timid:
                timid.append(img_arr)
            img_arr = img_set.read(h*w)

            
#And you can save them into png files
count = 1
for img in timid:
    png = Image.fromarray(np.reshape(list(img), (h,w)).astype('float32'), mode='L')
    png.save('Exe/Experiment 1/Train 2 Img/%d.png'%count)
    count += 1

In [3]:
from os import listdir
from PIL import Image
import os.path
import numpy as np

path_new = 'C:/Users/Admin/Downloads/HMM/Proper/Exe/Experiment 2/Train2'
h = 32 #height of image
w = 32 #width of image

#be careful with using this function, it will consume memory, access to disk and time
intruder = []
for f in listdir(path_new):
    with open(os.path.join(path_new, f), 'rb') as img_set:
        img_arr = img_set.read(h*w)
        while img_arr:
            if len(img_arr) == h*w and img_arr not in intruder:
                intruder.append(img_arr)
            img_arr = img_set.read(h*w)

            
#And you can save them into png files
count = 1
for img in intruder:
    png = Image.fromarray(np.reshape(list(img), (h,w)).astype('float32'), mode='L')
    png.save('Exe/Experiment 2/Train 2 Img/%d.png'%count)
    count += 1

In [4]:
timid

[b'MZ\xfe\x01\x81\x00\x00\x00 \x00\x00\x00\xff\xff\x00\x00\x00\x00S`\x00\x01\x00\x00\x1e\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00

In [5]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, Activation, Flatten
from tensorflow.keras.layers import Conv2D, MaxPooling2D
import numpy as np

#reshape images to fit into the CNN model
img_list = np.zeros(shape = (len(timid), h,w,1), dtype = np.uint8)
for j in range(len(timid)):
    img_list[j,:,:,0] = np.reshape(list(timid[j]), (h,w))
    
img_list = img_list.astype('float32')
img_list /= 255

In [6]:
#reshape images to fit into the CNN model
img_list1 = np.zeros(shape = (len(intruder), h,w,1), dtype = np.uint8)
for j in range(len(intruder)):
    img_list1[j,:,:,0] = np.reshape(list(intruder[j]), (h,w))
    
img_list1 = img_list1.astype('float32')
img_list1 /= 255

img_list1

array([[[[0.23137255],
         [0.1882353 ],
         [0.18039216],
         ...,
         [0.23137255],
         [0.03529412],
         [0.03529412]],

        [[0.2901961 ],
         [0.30588236],
         [0.3529412 ],
         ...,
         [0.31764707],
         [0.1254902 ],
         [0.23137255]],

        [[0.4509804 ],
         [0.39607844],
         [0.40392157],
         ...,
         [0.43137255],
         [0.45490196],
         [0.4117647 ]],

        ...,

        [[0.1254902 ],
         [0.30588236],
         [0.19215687],
         ...,
         [0.03529412],
         [0.03529412],
         [0.03529412]],

        [[0.05098039],
         [0.03921569],
         [0.03529412],
         ...,
         [0.37254903],
         [0.26666668],
         [0.32941177]],

        [[0.25490198],
         [0.1254902 ],
         [0.03529412],
         ...,
         [0.03529412],
         [0.03529412],
         [0.05098039]]],


       [[[0.03921569],
         [0.03529412],
         [0.03

In [9]:
x = np.array([i for i in img_list]+[i for i in img_list1])
model = Sequential()
#Conv2D Layers
model.add(Conv2D(12, (25, 25), padding='same',input_shape=(x).shape[1:], activation = 'relu'))
model.add(Conv2D(12, (25, 25), padding='same', activation = 'relu'))
#Max Pooling Layer
model.add(MaxPooling2D(pool_size=(2, 2)))
#Conv2D Layer
model.add(Conv2D(12, (13, 13), padding='same', activation = 'relu'))
model.add(Conv2D(12, (13, 13), activation = 'relu'))
#Max Pooling
model.add(MaxPooling2D(pool_size=(2, 2)))
#Flattening Layer
model.add(Flatten())
#Dense Layer
model.add(Dense(1024, activation = 'relu'))
model.add(Dense(1, activation = 'sigmoid'))

model.compile(loss='binary_crossentropy',
              optimizer='adam',
              metrics=['binary_accuracy'])

model.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d (Conv2D)              (None, 32, 32, 12)        7512      
_________________________________________________________________
conv2d_1 (Conv2D)            (None, 32, 32, 12)        90012     
_________________________________________________________________
max_pooling2d (MaxPooling2D) (None, 16, 16, 12)        0         
_________________________________________________________________
conv2d_2 (Conv2D)            (None, 16, 16, 12)        24348     
_________________________________________________________________
conv2d_3 (Conv2D)            (None, 4, 4, 12)          24348     
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 2, 2, 12)          0         
_________________________________________________________________
flatten (Flatten)            (None, 48)               

In [21]:
epochs = 100
labels = [0 for _ in img_list] + [1 for _ in img_list1]
model.fit(np.array(x), np.array(labels),
              epochs = epochs,
          validation_split = 0.25,
              shuffle = True)

Epoch 1/100
36/36 [==============================] - 34s 945ms/step - loss: 1.3506e-07 - binary_accuracy: 1.0000 - val_loss: 1.8306e-07 - val_binary_accuracy: 1.0000
Epoch 2/100
36/36 [==============================] - 35s 979ms/step - loss: 1.2808e-07 - binary_accuracy: 1.0000 - val_loss: 1.7305e-07 - val_binary_accuracy: 1.0000
Epoch 3/100
36/36 [==============================] - 40s 1s/step - loss: 1.2222e-07 - binary_accuracy: 1.0000 - val_loss: 1.6002e-07 - val_binary_accuracy: 1.0000
Epoch 4/100
36/36 [==============================] - 36s 1s/step - loss: 1.1598e-07 - binary_accuracy: 1.0000 - val_loss: 1.5509e-07 - val_binary_accuracy: 1.0000
Epoch 5/100
36/36 [==============================] - 37s 1s/step - loss: 1.1003e-07 - binary_accuracy: 1.0000 - val_loss: 1.5154e-07 - val_binary_accuracy: 1.0000
Epoch 6/100
36/36 [==============================] - 34s 954ms/step - loss: 1.0462e-07 - binary_accuracy: 1.0000 - val_loss: 1.4617e-07 - val_binary_accuracy: 1.0000
Epoch 7/100
3

36/36 [==============================] - 39s 1s/step - loss: 5.4778e-09 - binary_accuracy: 1.0000 - val_loss: 1.1904e-08 - val_binary_accuracy: 1.0000
Epoch 100/100
36/36 [==============================] - 42s 1s/step - loss: 5.3806e-09 - binary_accuracy: 1.0000 - val_loss: 1.1932e-08 - val_binary_accuracy: 1.0000


In [13]:
from os import listdir
from PIL import Image
import os.path
import numpy as np

path_new = 'C:/Users/Admin/Downloads/HMM/Proper/Exe/Experiment 1/Test2'
h = 32 #height of image
w = 32 #width of image

#be careful with using this function, it will consume memory, access to disk and time
timidtest = []
for f in listdir(path_new):
    with open(os.path.join(path_new, f), 'rb') as img_set:
        img_arr = img_set.read(h*w)
        while img_arr:
            if len(img_arr) == h*w and img_arr not in timidtest:
                timidtest.append(img_arr)
            img_arr = img_set.read(h*w)

            
#And you can save them into png files
count = 1
for img in timidtest:
    png = Image.fromarray(np.reshape(list(img), (h,w)).astype('float32'), mode='L')
    png.save('Exe/Experiment 1/Test Img/%d.png'%count)
    count += 1

In [14]:
from os import listdir
from PIL import Image
import os.path
import numpy as np

path_new = 'C:/Users/Admin/Downloads/HMM/Proper/Exe/Experiment 1/Test2'
h = 32 #height of image
w = 32 #width of image

#be careful with using this function, it will consume memory, access to disk and time
intrudertest = []
for f in listdir(path_new):
    with open(os.path.join(path_new, f), 'rb') as img_set:
        img_arr = img_set.read(h*w)
        while img_arr:
            if len(img_arr) == h*w and img_arr not in intrudertest:
                intrudertest.append(img_arr)
            img_arr = img_set.read(h*w)

            
#And you can save them into png files
count = 1
for img in intrudertest:
    png = Image.fromarray(np.reshape(list(img), (h,w)).astype('float32'), mode='L')
    png.save('Exe/Experiment 2/Test Img/%d.png'%count)
    count += 1

In [15]:
#reshape images to fit into the CNN model
img_testI = np.zeros(shape = (len(intrudertest), h,w,1), dtype = np.uint8)
for j in range(len(intrudertest)):
    img_testI[j,:,:,0] = np.reshape(list(intrudertest[j]), (h,w))
    
img_testI = img_testI.astype('float32')
img_testI /= 255

img_testI

array([[[[0.3019608 ],
         [0.3529412 ],
         [0.99607843],
         ...,
         [0.        ],
         [0.        ],
         [0.        ]],

        [[0.        ],
         [0.        ],
         [0.        ],
         ...,
         [0.        ],
         [0.        ],
         [0.        ]],

        [[0.        ],
         [0.        ],
         [0.        ],
         ...,
         [0.        ],
         [0.        ],
         [0.        ]],

        ...,

        [[0.23137255],
         [0.7647059 ],
         [0.23137255],
         ...,
         [0.23137255],
         [0.7647059 ],
         [0.23137255]],

        [[0.7647059 ],
         [0.23137255],
         [0.7647059 ],
         ...,
         [0.8509804 ],
         [0.2       ],
         [0.8509804 ]],

        [[0.2       ],
         [0.8509804 ],
         [0.2       ],
         ...,
         [0.8509804 ],
         [0.2       ],
         [0.8509804 ]]],


       [[[0.2       ],
         [0.8509804 ],
         [0.92

In [16]:
#reshape images to fit into the CNN model
img_testT = np.zeros(shape = (len(timidtest), h,w,1), dtype = np.uint8)
for j in range(len(timidtest)):
    img_testT[j,:,:,0] = np.reshape(list(timidtest[j]), (h,w))
    
img_testT = img_testT.astype('float32')
img_testT /= 255

img_testT

array([[[[0.3019608 ],
         [0.3529412 ],
         [0.99607843],
         ...,
         [0.        ],
         [0.        ],
         [0.        ]],

        [[0.        ],
         [0.        ],
         [0.        ],
         ...,
         [0.        ],
         [0.        ],
         [0.        ]],

        [[0.        ],
         [0.        ],
         [0.        ],
         ...,
         [0.        ],
         [0.        ],
         [0.        ]],

        ...,

        [[0.23137255],
         [0.7647059 ],
         [0.23137255],
         ...,
         [0.23137255],
         [0.7647059 ],
         [0.23137255]],

        [[0.7647059 ],
         [0.23137255],
         [0.7647059 ],
         ...,
         [0.8509804 ],
         [0.2       ],
         [0.8509804 ]],

        [[0.2       ],
         [0.8509804 ],
         [0.2       ],
         ...,
         [0.8509804 ],
         [0.2       ],
         [0.8509804 ]]],


       [[[0.2       ],
         [0.8509804 ],
         [0.92

In [22]:
predicted = model.predict(np.array([i for i in img_testI]+[i for i in img_testT]))
predicted, len(predicted)

(array([[0.0000000e+00],
        [1.0000000e+00],
        [1.0000000e+00],
        [1.0000000e+00],
        [1.0000000e+00],
        [0.0000000e+00],
        [4.0523369e-06],
        [0.0000000e+00],
        [1.0000000e+00],
        [1.0000000e+00],
        [1.0000000e+00],
        [1.0000000e+00],
        [0.0000000e+00],
        [0.0000000e+00],
        [1.0000000e+00],
        [1.0000000e+00],
        [1.0000000e+00],
        [1.0000000e+00],
        [9.1588104e-01],
        [0.0000000e+00],
        [1.0000000e+00],
        [1.0000000e+00],
        [1.0000000e+00],
        [1.0000000e+00],
        [0.0000000e+00],
        [0.0000000e+00],
        [1.0000000e+00],
        [1.0000000e+00],
        [1.0000000e+00],
        [1.0000000e+00],
        [4.7799196e-09],
        [0.0000000e+00],
        [1.0000000e+00],
        [1.0000000e+00],
        [1.0000000e+00],
        [1.0000000e+00],
        [0.0000000e+00],
        [0.0000000e+00],
        [1.0000000e+00],
        [1.0000000e+00],


In [23]:
pred=[]
for i in predicted:
    if i<0.5:
        pred.append(0)
    else:
        pred.append(1)
pred, len(pred)

([0,
  1,
  1,
  1,
  1,
  0,
  0,
  0,
  1,
  1,
  1,
  1,
  0,
  0,
  1,
  1,
  1,
  1,
  1,
  0,
  1,
  1,
  1,
  1,
  0,
  0,
  1,
  1,
  1,
  1,
  0,
  0,
  1,
  1,
  1,
  1,
  0,
  0,
  1,
  1,
  0,
  0,
  1,
  1,
  0,
  0,
  1,
  1,
  1,
  1,
  0,
  0,
  1,
  1,
  1,
  1,
  0,
  0,
  1,
  1,
  1,
  1,
  0,
  0,
  1,
  1,
  1,
  0,
  0,
  1,
  1,
  1,
  1,
  0,
  0,
  1,
  1,
  1,
  0,
  1,
  1,
  0,
  0,
  1,
  1,
  0,
  0,
  1,
  1,
  1,
  1,
  0,
  1,
  1,
  1,
  1,
  0,
  0,
  1,
  1,
  1,
  1,
  1,
  0,
  1,
  1,
  0,
  0,
  1,
  1,
  1,
  0,
  0,
  1,
  1,
  1,
  1,
  0,
  0,
  1,
  1,
  1,
  1,
  1,
  0,
  1,
  1,
  1,
  1,
  0,
  0,
  1,
  1,
  1,
  1,
  0,
  0,
  1,
  1,
  1,
  1,
  0,
  0,
  1,
  1,
  1,
  1,
  0,
  0,
  1,
  1,
  1,
  1,
  0,
  0,
  1,
  1,
  1,
  0,
  1,
  1,
  1,
  1,
  0,
  1,
  1,
  1,
  0,
  1,
  1,
  1,
  0,
  0,
  1,
  1,
  1,
  1,
  0,
  0,
  1,
  1,
  1,
  0,
  0,
  1,
  0,
  0,
  1,
  1,
  1,
  1,
  1,
  0,
  1,
  1,
  1,
  1,
  0,
  0,
  1,


In [24]:
oz=0
oo=0
zz=0
zo=0
for i,j in zip([1 for i in img_testI]+[0 for i in img_testT],pred):
    if i==0:
        if j==0:
            zz+=1
        else:
            zo+=1
    else:
        if j==0:
            oz+=1
        else:
            oo+=1
oo,oz,zo,zz

(200, 100, 200, 100)

In [25]:
accuracy = (oo+zz)/600
accuracy

0.5

In [26]:
200/600

0.3333333333333333

In [27]:
100/600

0.16666666666666666