In [1]:
from os import listdir
from PIL import Image
import os.path
import numpy as np

path_new = 'C:/Users/Admin/Downloads/HMM/Proper/Exe/Experiment 1/Train 1'
h = 32 #height of image
w = 32 #width of image

#be careful with using this function, it will consume memory, access to disk and time
timid = []
for f in listdir(path_new):
    with open(os.path.join(path_new, f), 'rb') as img_set:
        img_arr = img_set.read(h*w)
        while img_arr:
            if len(img_arr) == h*w and img_arr not in timid:
                timid.append(img_arr)
            img_arr = img_set.read(h*w)

            
#And you can save them into png files
count = 1
for img in timid:
    png = Image.fromarray(np.reshape(list(img), (h,w)).astype('float32'), mode='L')
    png.save('Exe/Experiment 1/Train 1 Img/%d.png'%count)
    count += 1

In [2]:
from os import listdir
from PIL import Image
import os.path
import numpy as np

path_new = 'C:/Users/Admin/Downloads/HMM/Proper/Exe/Experiment 2/Train1'
h = 32 #height of image
w = 32 #width of image

#be careful with using this function, it will consume memory, access to disk and time
intruder = []
for f in listdir(path_new):
    with open(os.path.join(path_new, f), 'rb') as img_set:
        img_arr = img_set.read(h*w)
        while img_arr:
            if len(img_arr) == h*w and img_arr not in intruder:
                intruder.append(img_arr)
            img_arr = img_set.read(h*w)

            
#And you can save them into png files
count = 1
for img in intruder:
    png = Image.fromarray(np.reshape(list(img), (h,w)).astype('float32'), mode='L')
    png.save('Exe/Experiment 2/Train 1 Img/%d.png'%count)
    count += 1

In [3]:
timid

[b'MZ\xfe\x01\x81\x00\x00\x00 \x00\x00\x00\xff\xff\x00\x00\x00\x00L\xe0\x00\x01\x00\x00\x1e\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\

In [4]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, Activation, Flatten
from tensorflow.keras.layers import Conv2D, MaxPooling2D
import numpy as np

#reshape images to fit into the CNN model
img_list = np.zeros(shape = (len(timid), h,w,1), dtype = np.uint8)
for j in range(len(timid)):
    img_list[j,:,:,0] = np.reshape(list(timid[j]), (h,w))
    
img_list = img_list.astype('float32')
img_list /= 255

In [5]:
#reshape images to fit into the CNN model
img_list1 = np.zeros(shape = (len(intruder), h,w,1), dtype = np.uint8)
for j in range(len(intruder)):
    img_list1[j,:,:,0] = np.reshape(list(intruder[j]), (h,w))
    
img_list1 = img_list1.astype('float32')
img_list1 /= 255

img_list1

array([[[[0.3019608 ],
         [0.3529412 ],
         [0.5686275 ],
         ...,
         [0.        ],
         [0.2       ],
         [0.00392157]],

        [[0.07058824],
         [0.        ],
         [0.3019608 ],
         ...,
         [0.        ],
         [0.        ],
         [0.        ]],

        [[0.        ],
         [0.        ],
         [0.        ],
         ...,
         [0.        ],
         [0.        ],
         [0.        ]],

        ...,

        [[0.        ],
         [0.        ],
         [0.        ],
         ...,
         [0.        ],
         [0.        ],
         [0.        ]],

        [[0.        ],
         [0.        ],
         [0.        ],
         ...,
         [0.        ],
         [0.        ],
         [0.        ]],

        [[0.        ],
         [0.        ],
         [0.        ],
         ...,
         [0.        ],
         [0.        ],
         [0.        ]]],


       [[[0.        ],
         [0.        ],
         [0.  

In [6]:
x = [i for i in img_list]+[i for i in img_list1]
model = Sequential()
#Conv2D Layers
model.add(Conv2D(4, (25, 25), padding='same',input_shape=(np.array(x)).shape[1:], activation = 'relu'))
model.add(Conv2D(4, (25, 25), padding='same', activation = 'relu'))
#Max Pooling Layer
model.add(MaxPooling2D(pool_size=(2, 2)))
#Conv2D Layer
model.add(Conv2D(4, (13, 13), padding='same', activation = 'relu'))
model.add(Conv2D(4, (13, 13), activation = 'relu'))
#Max Pooling
model.add(MaxPooling2D(pool_size=(2, 2)))
#Flattening Layer
model.add(Flatten())
#Dense Layer
model.add(Dense(124, activation = 'relu'))
model.add(Dense(1, activation = 'sigmoid'))

model.compile(loss='binary_crossentropy',
              optimizer='adam',
              metrics=['binary_accuracy'])

model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d (Conv2D)              (None, 32, 32, 4)         2504      
_________________________________________________________________
conv2d_1 (Conv2D)            (None, 32, 32, 4)         10004     
_________________________________________________________________
max_pooling2d (MaxPooling2D) (None, 16, 16, 4)         0         
_________________________________________________________________
conv2d_2 (Conv2D)            (None, 16, 16, 4)         2708      
_________________________________________________________________
conv2d_3 (Conv2D)            (None, 4, 4, 4)           2708      
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 2, 2, 4)           0         
_________________________________________________________________
flatten (Flatten)            (None, 16)                0

In [7]:
epochs = 30
labels = [0 for _ in img_list] + [1 for _ in img_list1]
model.fit(np.array(x), np.array(labels),
              epochs = epochs,
              validation_split = 0.25,
              shuffle = True)

Epoch 1/30
8/8 [==============================] - 4s 478ms/step - loss: 0.6683 - binary_accuracy: 0.5905 - val_loss: 0.7013 - val_binary_accuracy: 0.4941
Epoch 2/30
8/8 [==============================] - 3s 362ms/step - loss: 0.3503 - binary_accuracy: 0.8686 - val_loss: 0.3003 - val_binary_accuracy: 1.0000
Epoch 3/30
8/8 [==============================] - 3s 372ms/step - loss: 0.0598 - binary_accuracy: 1.0000 - val_loss: 0.0084 - val_binary_accuracy: 1.0000
Epoch 4/30
8/8 [==============================] - 3s 390ms/step - loss: 0.0096 - binary_accuracy: 0.9901 - val_loss: 7.3560e-06 - val_binary_accuracy: 1.0000
Epoch 5/30
8/8 [==============================] - 3s 381ms/step - loss: 0.0040 - binary_accuracy: 0.9980 - val_loss: 8.4850e-08 - val_binary_accuracy: 1.0000
Epoch 6/30
8/8 [==============================] - 3s 427ms/step - loss: 0.0114 - binary_accuracy: 0.9936 - val_loss: 2.4927e-07 - val_binary_accuracy: 1.0000
Epoch 7/30
8/8 [==============================] - 3s 428ms/step 

In [8]:
from os import listdir
from PIL import Image
import os.path
import numpy as np

path_new = 'C:/Users/Admin/Downloads/HMM/Proper/Exe/Experiment 1/Test2'
h = 32 #height of image
w = 32 #width of image

#be careful with using this function, it will consume memory, access to disk and time
timidtest = []
for f in listdir(path_new):
    with open(os.path.join(path_new, f), 'rb') as img_set:
        img_arr = img_set.read(h*w)
        while img_arr:
            if len(img_arr) == h*w and img_arr not in timidtest:
                timidtest.append(img_arr)
            img_arr = img_set.read(h*w)

            
#And you can save them into png files
count = 1
for img in timidtest:
    png = Image.fromarray(np.reshape(list(img), (h,w)).astype('float32'), mode='L')
    png.save('Exe/Experiment 1/Test Img/%d.png'%count)
    count += 1

In [9]:
from os import listdir
from PIL import Image
import os.path
import numpy as np

path_new = 'C:/Users/Admin/Downloads/HMM/Proper/Exe/Experiment 1/Test2'
h = 32 #height of image
w = 32 #width of image

#be careful with using this function, it will consume memory, access to disk and time
intrudertest = []
for f in listdir(path_new):
    with open(os.path.join(path_new, f), 'rb') as img_set:
        img_arr = img_set.read(h*w)
        while img_arr:
            if len(img_arr) == h*w and img_arr not in intrudertest:
                intrudertest.append(img_arr)
            img_arr = img_set.read(h*w)

            
#And you can save them into png files
count = 1
for img in intrudertest:
    png = Image.fromarray(np.reshape(list(img), (h,w)).astype('float32'), mode='L')
    png.save('Exe/Experiment 2/Test Img/%d.png'%count)
    count += 1

In [10]:
#reshape images to fit into the CNN model
img_testI = np.zeros(shape = (len(intrudertest), h,w,1), dtype = np.uint8)
for j in range(len(intrudertest)):
    img_testI[j,:,:,0] = np.reshape(list(intrudertest[j]), (h,w))
    
img_testI = img_testI.astype('float32')
img_testI /= 255

img_testI

array([[[[0.3019608 ],
         [0.3529412 ],
         [0.99607843],
         ...,
         [0.        ],
         [0.        ],
         [0.        ]],

        [[0.        ],
         [0.        ],
         [0.        ],
         ...,
         [0.        ],
         [0.        ],
         [0.        ]],

        [[0.        ],
         [0.        ],
         [0.        ],
         ...,
         [0.        ],
         [0.        ],
         [0.        ]],

        ...,

        [[0.23137255],
         [0.7647059 ],
         [0.23137255],
         ...,
         [0.23137255],
         [0.7647059 ],
         [0.23137255]],

        [[0.7647059 ],
         [0.23137255],
         [0.7647059 ],
         ...,
         [0.8509804 ],
         [0.2       ],
         [0.8509804 ]],

        [[0.2       ],
         [0.8509804 ],
         [0.2       ],
         ...,
         [0.8509804 ],
         [0.2       ],
         [0.8509804 ]]],


       [[[0.2       ],
         [0.8509804 ],
         [0.92

In [11]:
#reshape images to fit into the CNN model
img_testT = np.zeros(shape = (len(timidtest), h,w,1), dtype = np.uint8)
for j in range(len(timidtest)):
    img_testT[j,:,:,0] = np.reshape(list(timidtest[j]), (h,w))
    
img_testT = img_testT.astype('float32')
img_testT /= 255

img_testT

array([[[[0.3019608 ],
         [0.3529412 ],
         [0.99607843],
         ...,
         [0.        ],
         [0.        ],
         [0.        ]],

        [[0.        ],
         [0.        ],
         [0.        ],
         ...,
         [0.        ],
         [0.        ],
         [0.        ]],

        [[0.        ],
         [0.        ],
         [0.        ],
         ...,
         [0.        ],
         [0.        ],
         [0.        ]],

        ...,

        [[0.23137255],
         [0.7647059 ],
         [0.23137255],
         ...,
         [0.23137255],
         [0.7647059 ],
         [0.23137255]],

        [[0.7647059 ],
         [0.23137255],
         [0.7647059 ],
         ...,
         [0.8509804 ],
         [0.2       ],
         [0.8509804 ]],

        [[0.2       ],
         [0.8509804 ],
         [0.2       ],
         ...,
         [0.8509804 ],
         [0.2       ],
         [0.8509804 ]]],


       [[[0.2       ],
         [0.8509804 ],
         [0.92

In [12]:
predicted = model.predict(np.array([i for i in img_testI]+[i for i in img_testT]))
predicted, len(predicted)

(array([[0.0000000e+00],
        [1.0000000e+00],
        [1.0000000e+00],
        [1.0000000e+00],
        [1.0000000e+00],
        [0.0000000e+00],
        [3.3667088e-03],
        [0.0000000e+00],
        [1.0000000e+00],
        [1.0000000e+00],
        [1.0000000e+00],
        [1.0000000e+00],
        [0.0000000e+00],
        [0.0000000e+00],
        [1.0000000e+00],
        [1.0000000e+00],
        [1.0000000e+00],
        [1.0000000e+00],
        [2.5075851e-13],
        [0.0000000e+00],
        [1.0000000e+00],
        [1.0000000e+00],
        [1.0000000e+00],
        [1.0000000e+00],
        [0.0000000e+00],
        [0.0000000e+00],
        [1.0000000e+00],
        [1.0000000e+00],
        [1.0000000e+00],
        [1.0000000e+00],
        [2.7008021e-16],
        [0.0000000e+00],
        [1.0000000e+00],
        [1.0000000e+00],
        [1.0000000e+00],
        [1.0000000e+00],
        [0.0000000e+00],
        [0.0000000e+00],
        [1.0000000e+00],
        [1.0000000e+00],


In [13]:
pred=[]
for i in predicted:
    if i<0.5:
        pred.append(0)
    else:
        pred.append(1)
pred, len(pred)

([0,
  1,
  1,
  1,
  1,
  0,
  0,
  0,
  1,
  1,
  1,
  1,
  0,
  0,
  1,
  1,
  1,
  1,
  0,
  0,
  1,
  1,
  1,
  1,
  0,
  0,
  1,
  1,
  1,
  1,
  0,
  0,
  1,
  1,
  1,
  1,
  0,
  0,
  1,
  1,
  0,
  0,
  1,
  1,
  0,
  0,
  1,
  1,
  1,
  1,
  0,
  0,
  1,
  1,
  1,
  1,
  0,
  0,
  1,
  1,
  1,
  1,
  0,
  0,
  1,
  1,
  1,
  0,
  0,
  1,
  1,
  1,
  1,
  0,
  0,
  1,
  1,
  1,
  0,
  1,
  1,
  0,
  0,
  1,
  1,
  0,
  0,
  1,
  1,
  1,
  1,
  0,
  1,
  1,
  1,
  1,
  0,
  0,
  1,
  1,
  1,
  1,
  1,
  0,
  1,
  1,
  0,
  0,
  1,
  1,
  1,
  0,
  0,
  1,
  1,
  1,
  1,
  0,
  0,
  1,
  1,
  1,
  1,
  1,
  0,
  1,
  1,
  1,
  1,
  0,
  0,
  1,
  1,
  1,
  1,
  0,
  0,
  1,
  1,
  1,
  1,
  0,
  0,
  1,
  1,
  1,
  1,
  0,
  0,
  1,
  1,
  1,
  1,
  0,
  0,
  1,
  1,
  0,
  0,
  1,
  1,
  1,
  0,
  0,
  1,
  1,
  1,
  0,
  1,
  1,
  1,
  0,
  0,
  1,
  1,
  1,
  1,
  0,
  0,
  1,
  1,
  1,
  0,
  0,
  1,
  0,
  0,
  1,
  1,
  1,
  1,
  0,
  0,
  1,
  1,
  1,
  1,
  0,
  0,
  1,


In [14]:
oz=0
oo=0
zz=0
zo=0
for i,j in zip([1 for i in img_testI]+[0 for i in img_testT],pred):
    if i==0:
        if j==0:
            zz+=1
        else:
            zo+=1
    else:
        if j==0:
            oz+=1
        else:
            oo+=1
oo,oz,zo,zz

(194, 106, 194, 106)

In [15]:
accuracy = (oo+zz)/600
accuracy

0.5

In [16]:
238/600

0.39666666666666667

In [79]:
62/600

0.10333333333333333